export const addStudentValues = {
  admission_no: "",
  student_name: "",
  class_name: "",
  section: "",
  roll_no: "",
  father_name: "",
  mother_name: "",
  date_of_birth: "",
  address: "",
  alternative_phone_no: "",
  father_occupation: "",
  mother_occupation: "",
  religion: "",
  gender: "",
  email: "",
  password: "",
  phone: "",
  date_of_admission: "",
  reserve_category: "",
  student_image:null,
  blood_group: "",
  quota: "",
  ews: "",
  bpl: "",
  height: "",
  weight: "",
};
export const addStaffValues = {
  staff_name: "",
  password: "",
  phone: "",
  email: "",

  address: "",
  gender: "",
  religion: "",
  avatar:null,
  
  role:'',
  designation:"",
  qualification:"",
  experience: "",
  bacnk_account_number: "",
  ifsc_code: "",
  pan_card_no: "",
  joining_date: "",
};
